// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamlPowerToys
{
    static class Vsix
    {
        public const string Id = "d01c1624-8838-4097-bf77-f52d73fc7a1f";
        public const string Name = "XAML Power Toys for Visual Studio 2015 - 2017";
        public const string Description = @"Visual Studio 2015 - 2017 extension that enables developers to rapidly generate data entry forms from view models or entity objects for Xamarin Forms, UPW, WPF, and Silverlight.";
        public const string Language = "en-US";
        public const string Version = "1.5.28";
        public const string Author = "Karl Shifflett";
        public const string Tags = "xaml, xaml power toys, code generation, wpf, uwp, xamarin, silverlight";
    }
}
