// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamlPowerToys
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidXamlPowerToysCommandPackageString = "fec33645-eb1c-423e-843f-7bd8ddf9e0d0";
        public const string guidXamlCmdSetString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public const string guidXamarinXamlCmdSetString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public const string guidImagesString = "b4a03163-4e05-460c-97ff-a8a943442754";
        public static Guid guidXamlPowerToysCommandPackage = new Guid(guidXamlPowerToysCommandPackageString);
        public static Guid guidXamlCmdSet = new Guid(guidXamlCmdSetString);
        public static Guid guidXamarinXamlCmdSet = new Guid(guidXamarinXamlCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int editorContextMenu = 0x0103;
        public const int MyMenuGroup = 0x1020;
        public const int XamlPowerToysCommandId = 0x0100;
        public const int codeEditorContextMenu = 0x040D;
        public const int XamarinMenuGroup = 0x1020;
        public const int XamarinXamlPowerToysCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
